# Generated by Django 2.0.5 on 2018-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('test_enviroment_id', models.IntegerField()),
                ('test_template', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Created'), ('P', 'Passed'), ('F', 'Failed')], default='C', max_length=1)),
                ('log_information', models.TextField()),
            ],
        ),
    ]
