# Generated by Django 2.0.5 on 2018-05-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='log_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
