# Generated by Django 2.0.5 on 2018-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180510_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_script',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
